language: java

sudo: false

jdk:
 - oraclejdk8 
 - oraclejdk7

branches:
  only:
    - master

before install:

-git clone https://github.com/LEDS/sincap-entities.git
-cd sincap-entities
-mvn test

script: mvn test
