language: java

sudo: false

jdk:
 - oraclejdk8 
 - oraclejdk7

branches:
  only:
    - master
	
script: 
  - git clone https://github.com/LEDS/sincap-entities.git
  - cd sincap-entities
  - mvn test
  - cd ../sincap-interface-web
  - mvn test
