language: java

sudo: false

jdk:
 - oraclejdk8 
 - oraclejdk7

branches:
  only:
    - master

before_script:
  - git clone https://github.com/LEDS/sincap-entities.git
  - cd sincap-entities
  - mvn clean install
  - cd ../sincap-interface-web
 	
script: mvn test
