language: java

jdk:
 - oraclejdk8 
 - oraclejdk7
 
addons:
 -postgresql: "9.3"

services: postgresql

#before_script:
 #- psql -c "DROP DATABASE IF EXISTS sincap_teste;" -U postgres
 #- psql -c "CREATE DATABASE sincap_teste;" -U postgres
 #- psql -U postgres -d sincap_teste -f src/main/resources/sincapBackup.sql
 
branches:
  only:
    - master
    - development

after_success:
  - mvn sonar:sonar

notifications:
  slack: leds:Bdewxwg54FgRsFjl9zN5iRFI
